version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/wrappers/rust/regorust"
    schedule:
      interval: "weekly"
    groups:
      cargo:
        patterns:
          - "*"

  - package-ecosystem: "nuget"
    directory: "/wrappers/dotnet"
    schedule:
      interval: "weekly"
    groups:
      nuget:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/wrappers/python"
    schedule:
      interval: "weekly"
    groups:
      pip:
        patterns:
          - "*"
