name: Build Python Wheels for Release

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build ${{ matrix.python }} wheels for ${{ matrix.target }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        python: [cp39, cp310, cp311, cp312, cp313, cp314]
        target:
          - windows
          - macos-arm64
          - macos-x86_64
          - manylinux-x86_64
          - manylinux-aarch64
          - musllinux-x86_64
          - musllinux-aarch64
        exclude:
          - python: cp39
            target: macos-arm64
          - python: cp39
            target: macos-x86_64
        include:
          - target: windows
            runner: windows-latest
            archs: AMD64
            build: "win*"
            before_all: ""
            environment: ""
            macos_deployment_target: ""
          - target: macos-arm64
            runner: macos-latest
            archs: arm64
            build: "macosx*"
            before_all: brew install openssl@3
            environment: "OPENSSL_ROOT_DIR=$(brew --prefix openssl@3)"
            macos_deployment_target: "15.0"
          - target: macos-x86_64
            runner: macos-15-intel
            archs: x86_64
            build: "macosx*"
            before_all: brew install openssl@3
            environment: "OPENSSL_ROOT_DIR=$(brew --prefix openssl@3)"
            macos_deployment_target: "15.0"
          - target: manylinux-x86_64
            runner: ubuntu-latest
            archs: x86_64
            build: "manylinux*"
            before_all: dnf makecache && dnf install -y openssl-devel
            environment: ""
            macos_deployment_target: ""
          - target: manylinux-aarch64
            runner: ubuntu-24.04-arm
            archs: aarch64
            build: "manylinux*"
            before_all: dnf makecache && dnf install -y openssl-devel
            environment: ""
            macos_deployment_target: ""
          - target: musllinux-x86_64
            runner: ubuntu-latest
            archs: x86_64
            build: "musllinux*"
            before_all: apk add openssl-dev
            environment: ""
            macos_deployment_target: ""
          - target: musllinux-aarch64
            runner: ubuntu-24.04-arm
            archs: aarch64
            build: "musllinux*"
            before_all: apk add openssl-dev
            environment: ""
            macos_deployment_target: ""

    steps:
      - uses: actions/checkout@v6

      - name: Git config for fetching pull requests
        run: |
          git config --global --add remote.origin.fetch +refs/pull/*/merge:refs/remotes/pull/*

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.4.1
        env:
          CIBW_ARCHS: ${{ matrix.archs }}
          CIBW_BEFORE_ALL: ${{ matrix.before_all }}
          CIBW_BUILD: ${{ matrix.python }}-${{ matrix.build }}
          CIBW_ENVIRONMENT: >
            REGOCPP_REPO=https://github.com/${{github.repository}}
            REGOCPP_TAG=${{github.sha}}
            ${{ matrix.environment }}
          CIBW_MANYLINUX_AARCH64_IMAGE: manylinux_2_34
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_34
          MACOSX_DEPLOYMENT_TARGET: ${{ matrix.macos_deployment_target }}
        with:
          package-dir: ${{github.workspace}}/wrappers/python/

      - uses: actions/upload-artifact@v7
        with:
          name: wheels-${{ matrix.python }}-${{ matrix.target }}
          path: ./wheelhouse/*.whl

  merge:
    needs: build_wheels
    runs-on: ubuntu-latest
    steps:
      - name: Download Wheels
        uses: actions/download-artifact@v8
        with:
          path: wheelhouse
          pattern: wheels-*
          merge-multiple: true
      - run: ls -R wheelhouse
      - uses: actions/upload-artifact@v7
        with:
          name: wheels
          path: ./wheelhouse/*
