name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-test:
    strategy:
      matrix:
        platform: [ "ubuntu-latest" ]
        build-type: [ "Release", "Debug" ]
        
        include:
        - platform: "ubuntu-latest"
          cmake-flags: "-G Ninja -DCMAKE_INSTALL_PREFIX=dist"
          dependencies: "sudo apt install ninja-build"
    
      # Don't abort runners if a single one fails
      fail-fast: false

    runs-on: ${{matrix.platform}}

    steps:
    - uses: actions/checkout@v3
    
    - name: Install build dependencies
      run: ${{ matrix.dependencies }}
      
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build-type}} ${{matrix.cmake-flags}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build-type}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.build-type}} --output-on-failure --timeout 400 --interactive-debug-mode 0 
